# Generated by Django 4.2.11 on 2024-04-05 08:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_username_alter_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('restaurants', 'Restaurants'), ('bars', 'Bars'), ('events', 'Events'), ('whats on', 'Whats On')], max_length=100), blank=True, size=None),
        ),
    ]
