# Generated by Django 4.2.11 on 2024-04-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_savedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
