# Generated by Django 4.2.11 on 2024-04-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='button_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
