# Generated by Django 4.2.11 on 2024-04-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_button_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='button_color',
        ),
    ]
