# Generated by Django 4.2.11 on 2024-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_alter_rsvp_num_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='num_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
    ]
