# Generated by Django 4.2.11 on 2024-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
