# Generated by Django 4.2.11 on 2024-04-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_post_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='event',
        ),
    ]
