# Generated by Django 4.2.11 on 2024-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0014_remove_post_image_alter_savedpost_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Archived')], default=0),
        ),
    ]
