# Generated by Django 4.2.11 on 2024-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0015_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
