# Generated by Django 4.2.11 on 2024-04-22 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_management', '0016_post_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedpost',
            name='button_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='likedpost',
            unique_together={('user', 'post')},
        ),
    ]
