# Generated by Django 4.2.11 on 2024-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_post_tag'),
        ('event_management', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='posts',
            field=models.ManyToManyField(to='content_management.post'),
        ),
    ]
