# Generated by Django 4.2.11 on 2024-04-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_event_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='posts',
        ),
    ]
