# Generated by Django 4.2.11 on 2024-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
