# Generated by Django 4.2.11 on 2024-04-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
